### ISSUE TITLE
02_ocp_packer_image failed to validate  outscale.pkr.hcl  file

### ISSUE THREAD

**Issue by aminestm** [davmartini/ocp_outscale#1]
Hey David ,
Please can you validate this from your end , thanks 

packer validate outscale.pkr.hcl 
Error: Unknown source type osc-bsusurrogate

  on  line 0:
  (source code not available)

known builders: [vsphere-clone amazon-ebssurrogate yandex lxc docker azure-arm
parallels-pvm outscale-bsuvolume outscale-chroot proxmox-clone amazon-ebsvolume
linode vmware-iso vsphere-iso qemu hyperv-vmcx virtualbox-vm hcloud openstack
ucloud-uhost amazon-instance parallels-iso outscale-bsu oracle-classic
virtualbox-iso lxd virtualbox-ovf proxmox-iso azure-dtl cloudstack profitbricks
googlecompute ncloud amazon-ebs outscale-bsusurrogate triton digitalocean
jdcloud vagrant hyperone oracle-oci hyperv-iso oneandone alicloud-ecs proxmox
file null tencentcloud-cvm azure-chroot amazon-chroot vmware-vmx]

packer plugins installed              
/Users/.config/packer/plugins/github.com/hashicorp/outscale/packer-plugin-outscale_v1.0.2_x5.0_darwin_arm64

Regards,
Amine

**Comment by clementcohen** [comment]
Hello Amine, 
i'm not a member  of Outscale only a customer like you (maybe),  but as i'm facing the same issue  today,  I respond :) 

there's an error on the  hcl  file  look at your known builders  it's  **outscale**-bsusurrogate  instead of **osc**-bsusurrogate ;)

**Comment by davmartini** [comment]
Hi Amine,
It's strange because I'm using this Packer plugin : https://www.packer.io/plugins/builders/outscale/bsusurrogate
The name mentioned is clearly **osc-bsusurrogate**

**Comment by clementcohen** [comment]
I open an issue  to outscale 
 name need to be  change as  the plugins is now external ( see https://github.com/outscale/packer-plugin-outscale/issues/76 )

**Comment by davmartini** [comment]
Hi,
I updated code to take in charge new outscale plugin name and new repo URL.
I also update OMI image because used Fedora isn't available yet.
